---
- name: Configure application
  copy: content="{{ item.value }}"
        dest="{{ envdir_home }}/{{ item.key }}"
        owner=root
        group=mmw
        mode=0750
  with_dict: app_config
  notify:
    - Restart mmw-app

- name: Configure Gunicorn settings
  template: src=gunicorn.py.j2 dest=/etc/mmw.d/gunicorn.py
  notify:
    - Restart mmw-app

- name: Configure service definition
  template: src=upstart-app.conf.j2 dest=/etc/init/mmw-app.conf
  notify:
    - Restart mmw-app
