---
- name: Create folders for static files
  file: path={{ item }}
        state=directory
        owner={{ ansible_ssh_user }}
        group=mmw
        mode=0775
  with_items:
    - "{{ app_static_root }}"
    - "{{ app_media_root }}"
    - "{{ app_static_cache }}"

- name: Install application javascript dependencies
  command: npm install
  args:
    chdir: "{{ app_home }}"
  sudo: False

- name: Create static files and run collectstatic (staging/production)
  command: ./bundle.sh
  args:
    chdir: "{{ app_home }}"
  environment: app_config
  sudo: False
  when: "['development'] | is_not_in(group_names)"

- name: Create static files and run collectstatic (development)
  command: ./bundle.sh --debug
  args:
    chdir: "{{ app_home }}"
  environment: app_config
  sudo: False
  when: "['development'] | is_in(group_names)"

- name: Run Django collectstatic command
  command: ./manage.py collectstatic --noinput
  sudo: False
  args:
    chdir: "{{ app_home }}"
  environment: app_config

- name: Create JS test harness
  template: src=testem-harness.html.j2
            dest={{ app_static_root }}/test.html
  sudo: False
  when: "['development', 'test'] | some_are_in(group_names)"
