---
app_home: /opt/app
app_config_home: /etc/mmw.d/env
app_deploy_branch: "master"

app_config:
  MMW_DB_NAME: "{{ postgresql_database }}"
  MMW_DB_USER: "{{ postgresql_username }}"
  MMW_DB_PASSWORD: "{{ postgresql_password }}"
  MMW_DB_HOST: "{{ postgresql_host }}"
  MMW_DB_PORT: "{{ postgresql_port }}"
  MMW_TEST_DB_NAME: "{{ django_test_database }}"
  MMW_STATSD_HOST: "{{ statsite_host }}"
  MMW_CACHE_HOST: "{{ redis_host }}"
  MMW_CACHE_PORT: "{{ redis_port }}"
  DJANGO_SETTINGS_MODULE: "{{ django_settings_module }}"
  DJANGO_STATIC_ROOT: "{{ app_static_root }}"
  DJANGO_MEDIA_ROOT: "{{ app_media_root }}"
  DJANGO_POSTGIS_VERSION: "{{ app_postgis_version }}"
  DJANGO_SECRET_KEY: "{{ app_secret_key }}"

app_log: /var/log/mmw-app.log
app_log_rotate_count: 5
app_log_rotate_interval: daily

app_gunicorn_log: /var/log/mmw-gunicorn.log
app_gunicorn_log_rotate_count: 5
app_gunicorn_log_rotate_internal: daily

app_static_root: /var/www/mmw/static/
app_media_root: /var/www/mmw/media/

app_static_cache: /var/cache/mmw/static/

app_postgis_version: 2.1.3
app_secret_key: "{{ postgresql_password | md5 }}"
