---
dependencies:
  - { role: "model-my-watershed.base" }
  - { role: "azavea.nodejs" }
  - { role: "azavea.mapnik" }
  - { role: "model-my-watershed.monitoring", collectd_prefix: "collectd.tiler.", when: "['test'] | is_not_in(group_names)" }
  - { role: "model-my-watershed.nginx" }
