---
- name: Restart mmw-app
  service: name=mmw-app state=restarted
  when: "['app-servers'] | is_in(group_names)"

- name: Restart Celery
  service: name=celeryd state=restarted
  when: "['workers'] | is_in(group_names)"

